### ISSUE TITLE
License

### ISSUE THREAD

**Issue by davidbrochart** [alexdelorenzo/aiopath#24]
Would you be open to re-license to a more permissive license, like MIT or BSD?

**Comment by Zocker1999NET** [comment]
duplicate of #21 (but maintainer didn‘t answered there too yet)

**Comment by davidbrochart** [comment]
Thanks, let's close this one then.
BTW, [AnyIO](https://anyio.readthedocs.io/en/3.x/fileio.html#asynchronous-path-operations) provides async path operations, and is MIT licensed.
