### ISSUE TITLE
typing.Literal requires Python 3.8

### ISSUE THREAD

**Issue by sarumpaet** [alexdelorenzo/aiopath#3]
https://github.com/alexdelorenzo/aiopath/blob/2a795befc4440425d766ac39c379e8fecc43575d/aiopath/path.py#L5
https://docs.python.org/3/library/typing.html#typing.Literal
...but README.md dependencies only mention Python 3.7:
https://github.com/alexdelorenzo/aiopath/blob/main/README.md#dependencies

**Comment by alexdelorenzo** [comment]
Good catch, I thought the backported `typing` module on PyPI would have `Literal` and `Final` definitions, but it doesn't. 

`aiopath==0.5.1` should fix this issue, although I haven't tested it on older Python versions.

You can install it like so:
```bash
python3 -m pip install aiopath==0.5.1
```

**Comment by alexdelorenzo** [comment]
I tested `aiopath==0.5.3` on Python 3.7.10 and it seems to work on my end.

**Comment by alexdelorenzo** [comment]
I'm going to close this issue as it seems to be resolved in `v0.5.3` and up.

Thanks for submitting a bug report, @sarumpaet. Feel free to comment or open a new issue if you're still experiencing problems with `aiopath`.
